theme = "paper"
baseURL = "https://yota22721.github.io/"
languageCode = 'en-us'
title = 'YouTai'

[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
	#color style
	#color = 'light'

	#header social icons
	twitter = 'yota0x86'
	github = 'yota22721'
	rss = true

	#home page profile
	avatar = "https://avatars.githubusercontent.com/u/89376495?v=4"
	name = 'youtai'
	bio = 'Security enthusiast'

	#misc
	monoDarkIcon = true

[menu]
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about"
	weight = 10
	
[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/posts"
	weight = 10

